version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
    - .:/usr/src/app

  db:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:${MONGO_INITDB_PORT}'
    volumes:
      - data:/data/db

volumes: 
 data: {}